### ISSUE TITLE
Post Comments link lining up next to tags

### ISSUE THREAD

**Issue by jamigibbs** [jamigibbs/scribe#1]
Add the following to resolve:

``` CSS
.comments-link { display: block; }
```

![screen shot 2016-06-09 at 4 15 23 pm](https://cloud.githubusercontent.com/assets/872479/15946660/67ab1adc-2e5d-11e6-92c0-0c813dce7a6e.png)
